### ISSUE TITLE
Javascript actions not work properly when the page initializes.

### ISSUE THREAD

**Issue by tirnavali** [arielj/vanilla-nested#12]
Javascript actions not work properly when the page initializes.
After refreshing page one time everything becomes normal.
Maybe this problem because of webpacker wrong loading order of  js files. How can i solve this?

**application.js file**
```
require("vanilla-nested")
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery")
require("popper.js")
```

**Comment by arielj** [comment]
Can you try this way of importing the js and putting it after the other requires? it is working in the test app

https://github.com/arielj/vanilla-nested/blob/master/test/VanillaNestedTests/app/javascript/packs/application.js#L19

**Comment by tirnavali** [comment]
**I tried it does not work either. Look at the gif below .The page needs refreshing for javascript to work all the time.**


![2021-03-19-23-35-38](https://user-images.githubusercontent.com/58842032/111839448-da986c80-890b-11eb-8bff-bdb14c1bf327.gif)

**Comment by arielj** [comment]
> **I tried it does not work either. Look at the gif below .The page needs refreshing for javascript to work all the time.**
> 
> ![2021-03-19-23-35-38](https://user-images.githubusercontent.com/58842032/111839448-da986c80-890b-11eb-8bff-bdb14c1bf327.gif)

thanks for the clear report with the gif, I'll push a fix today, it's an issue with how turbolinks handles the page load events

**Comment by arielj** [comment]
@tirnavali can you try updating the js code now?

```
rails webpacker:clobber
yarn upgrade vanilla-nested
```

that should clear webpacker cache, then update the vanilla-nested js module with the latest changes on master

**Comment by tirnavali** [comment]
I tried it is working. Thank you.
