### ISSUE TITLE
When on new form or edit form view, refreshing the form is breaking link_to_remove_nested's behavior.

### ISSUE THREAD

**Issue by tirnavali** [arielj/vanilla-nested#44]
When on new form or edit form view, refreshing the form is breaking link_to_remove_nested's behavior. Rails 7.

**Comment by arielj** [comment]
hey @tirnavali do you have some step-by-step instructions or a test app? thanks

**Comment by tirnavali** [comment]
https://user-images.githubusercontent.com/58842032/155014400-f601fa89-8a23-4c65-b2b2-7b0683fbe9b5.mov

**Comment by arielj** [comment]
I see the video shows the `sel` error reported here https://github.com/arielj/vanilla-nested/issues/43, but I understood that got fixed, is that still not fixed?

Probably after fixing that issue the remove_nested works again, I'll try to get that fixed today.

**Comment by arielj** [comment]
hey @tirnavali can you try with the latest 1.6.0 release? it includes the `sel` error fix

**Comment by tirnavali** [comment]
Works very well with this upgrade thank you @arielj 👏🏻
