### ISSUE TITLE
display: initial after undo

### ISSUE THREAD

**Issue by itsyoshio** [arielj/vanilla-nested#48]
Why is the style display: initial; set after undo?

Is there a way to prevent this from being added?\
As of now, it's breaking my styling

**Comment by arielj** [comment]
hmmm it's because it's first hidden with `display: none` and I have to remove that, I'll think of a different way to do that (I'll see if I can store the current `display` value before hidding it so I can revert back to the original instead of `initial`

**Comment by arielj** [comment]
One thing you can try for now as a workaround (while I find some time to fix it) is to listen to the `undo` event and fix the display value https://github.com/arielj/vanilla-nested#vanilla-nestedfields-hidden-undo

**Comment by arielj** [comment]
hey @itsyoshio, I released version 1.6.1 that should fix this issue, can you confirm? check the Updating section here https://github.com/arielj/vanilla-nested/tree/1.6.1#updating

**Comment by itsyoshio** [comment]
Working perfectly! Thanks :)
