### ISSUE TITLE
Allow for custom Class on removed Elements.

### ISSUE THREAD

**Issue by itsyoshio** [arielj/vanilla-nested#51]
Whenever a preexisting Element is removed, the `.wrapper-div` is preserved and a hidden _delete Input is inserted.\
It would be great if one could add a class to the `.wrapper-div` (maybe `vanilla-nested-removed` (extra d)).\

This would be helpful to me, because i am generating a dynamic grid that can scroll horizontally.\
The `.wrapper-div`'s are taking a space in the Grid even when empty (width 0)

**Comment by arielj** [comment]
Hey @itsyoshio, sorry it took me so long to answer, I was on vacations when I saw this and then I forgot about it.

I imagine you can do what you want using the `vanilla-nested:fields-removed` event: https://github.com/arielj/vanilla-nested#vanilla-nestedfields-removed if I understand you correctly.

You can add an event listener and use `event.target.classList.add("vanilla-nested-removed")`.

Something like:

```js
document.addEventListener('vanilla-nested:fields-removed', (e) => {
  event.target.classList.add("vanilla-nested-removed")
})
```

**Comment by itsyoshio** [comment]
Works like an absolute charm, greatly appreciated!
