### ISSUE TITLE
Potential visual bug when deleting child item when item is not managed by vanilla nested

### ISSUE THREAD

**Issue by alex-benoit** [arielj/vanilla-nested#66]
Steps to repeat
- Render a list with already one child element
- Destroy the element
- Not all elements gets removed from DOM (this can create issues is wrapping div has padding/margin)

**Comment by arielj** [comment]
Can you elaborate a bit more? I'm not able to reproduce the issue but maybe I'm not doing the right steps.

Would be useful to know what's your code, how it looks when rendered, what the log in the server when you submit the form, etc.

**Comment by alex-benoit** [comment]
Yes of course!

Using import maps on chrome/brave, no console errors.

`@checkin` has_many `@priorities`
`@checkin.priorities.new` in controller (to have already one empty association - can also be just a render call to the fields partial from view)

View
```html
<%= simple_form_for @checkin do |f| %>
...
<div id="priorities">
  <%= f.simple_fields_for :priorities do |g| %>
    <%= render 'priority_fields', form: g %>
  <% end %>
</div>

<%= link_to_add_nested f, :priorities, '#priorities', link_text: 'Add Another Priority', link_classes: 'btn btn-secondary' %>
```

Form:
```html
<div class="input-group mb-3">
  <input type="text" class="form-control">
  <%= link_to_remove_nested(form) %>
</div>
```

On first render:
````html
<div id="priorities">
  <div class="input-group mb-3">
    <input type="text" />
    <input autocomplete="off" name="checkin[priorities_attributes][0][_destroy]" type="hidden" value="0" />
    <a data-undo-text="Undo" data-undo-link-classes="">X</a>
  </div>
</div>
```

Add new child (not necessary step):
```html
<div id="priorities">
  <div class="input-group mb-3">
    <input type="text" class="form-control">
    <input value="0" autocomplete="off" type="hidden" name="checkin[priorities_attributes][0][_destroy]" id="checkin_priorities_attributes_0__destroy">
    <a class=" vanilla-nested-remove " data-undo-text="Undo" data-undo-link-classes="">X</a>
  </div>

  <div class="input-group mb-3 added-by-vanilla-nested">
    <input type="text" class="form-control">
    <input value="0" autocomplete="off" type="hidden" name="checkin[priorities_attributes][1666397039331][_destroy]" id="checkin_priorities_attributes_1666397039331__destroy">
    <a class=" vanilla-nested-remove " data-undo-text="Undo" data-undo-link-classes="">X</a>
  </div>
</div>
```

Delete element not rendered by vanilla
```html
<div id="priorities">
  <div class="input-group mb-3">
    <input value="1" autocomplete="off" type="hidden" name="checkin[priorities_attributes][0][_destroy]" id="checkin_priorities_attributes_0__destroy">
  </div>

  <div class="input-group mb-3 added-by-vanilla-nested">
    <input type="text" class="form-control">
    <input value="0" autocomplete="off" type="hidden" name="checkin[priorities_attributes][1666397039331][_destroy]" id="checkin_priorities_attributes_1666397039331__destroy">
    <a class=" vanilla-nested-remove " data-undo-text="Undo" data-undo-link-classes="">X</a>
  </div>
</div>
```

There should only be one div remaining. The only difference I can see is the missing `added-by-vanilla-nested`.

**Comment by alex-benoit** [comment]
Quick follow-up, I suspect it's caused by

https://github.com/arielj/vanilla-nested/blob/083064c6985578e1747d62b27ab05d46eaf28728/app/assets/javascripts/vanilla_nested.js#L62-L69

I assume it's because if the field was already there, a flag needs to exist to destroy the record. The little side effect I am seeing is my `mb-3` margin bottom class on the wrapper still exists despite the `wrapper.innerHTML = '';` hence why fantom spacing exists.

This is a super edge case where I am trying to start with one empty field, but will also happen if removing record where the wrapper has padding/margin.

Potential suggestions:
- Use the docs to indicate to not put margin/padding on the wrapper
- Resetting the padding/margin on the wrapper
- Instead of emptying out the HTML and adding the remove flag, removing the wrapper and adding the flag without wrapper

**Comment by alex-benoit** [comment]
I'm going to reopen an new issue and close this one, as the source of the problem has changed!
