### ISSUE TITLE
Link does not work for me in rails 7

### ISSUE THREAD

**Issue by Bog2G** [arielj/vanilla-nested#69]
For some reason no matter what i do the link won't generate anything and it does not give me any errors.

Here is my repo if that's needed https://github.com/Bog2G/PollSite

Thanks in advance !

**Comment by arielj** [comment]
Do you have any error in the browser's dev tools after pressing the link?

**Comment by arielj** [comment]
I'm testing your app, you have two problems:
- your bootstrap setup is messed up and that makes vanilla-nested's js to not even load (there's a boostrap error in the console, after removing bootstrap from the app I can see an error when clicking the Add question button)
- you are using `'#questions'` as the selector in the `link_to_add_nested` call, but your div doesn't have a `questions` id, it has a `questions` class, so either use an ID in the div or change the selector to `.questions` (I'd recommend an id)

**Comment by arielj** [comment]
After removing bootstrap and fixing the div to have `id="questions"` instead of `class="questions"` this works just fine, so it's not an issue in the gem, so I'm closing this.

**Comment by Bog2G** [comment]
Thank you very much for your assistance! Sorry if my question seemed silly, I'm still a big noob especially at making sites.
